---
- name: Подготовка к публикации
  tags: prepare_step
  block:
    - name: Создание директорий для хранения конфигураций и vrd файлов
      ansible.builtin.file:
        path: "{{ path_to_temp_files }}/{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ list_temp_directories }}"

    - name: Определение имени дистрибутива 1c
      ansible.builtin.set_fact:
        file_name_1c: "server64_{{ version_1c | replace('.', '_') }}.tar.gz"

- name: Получение дистрибутива 1С
  tags: not_clean
  block:
    - name: Загружаем дистрибутив 1С
      ansible.builtin.get_url:
        url: "ftp://{{ ftp.user }}:{{ ftp.password }}@{{ ftp.path }}/{{ version_1c }}/{{ file_name_1c }}"
        dest: "{{ path_to_temp_files }}/distribution"
        mode: "0755"
  # rescue:
  #   - name: Копируем предварительно записанный дистрибутив

- name: Создание файлов для сборки
  tags: vrd
  block:
    - name: Создание WEB публикаций
      ansible.builtin.include_tasks: "../services/create_conf_vrd_file.yml"
      loop: "{{ databases }}"
      loop_control:
        loop_var: item
      vars:
        database: "{{ item.database }}"
        server: "{{ item.server }}"
        url: "{{ item.url }}"
        type_vrd: "{{ item.type }}"

    - name: Создание Dockerfile и конфигурации apache2
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ path_to_temp_files }}"
        owner: grushevskyv
        group: grushevskyv
        mode: "0644"
      loop:
        - Dockerfile
        - apache2.conf

- name: Работаем с images
  tags: image
  block:
    - name: Обновляем image httpd
      community.docker.docker_image:
        name: httpd
        source: pull
        tag: 2.4
        pull:
          platform: amd64

    - name: Собираем image
      community.docker.docker_image:
        name: "{{ web_1c_service.image }}"
        tag: latest
        force_source: true
        force_tag: true
        push: "{{ web_1c_service.is_push }}"
        build:
          path: "{{ path_to_temp_files }}"
          dockerfile: "{{ path_to_temp_files }}/Dockerfile"
        source: build
      notify: Cleaner
